TrafficLightControllerSimulator2/Controllers/HomeController.cs
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrafficLightControllerSimulator2.Controllers
{
    public class HomeController : Controller
    {
        TrafficLightSimulatorService Service = TrafficLightSimulatorService.GetInstance;
        public ActionResult Index()
        {
            var trafficLight = Service.GetTrafficLight();
            ViewBag.On = trafficLight.On;

            ViewBag.PresetGreenLightTimeLeft = trafficLight.PresetGreenLightTimeLeft;
            ViewBag.PresetRedLightTimeLeft = trafficLight.PresetRedLightTimeLeft;
            ViewBag.PresetYellowLightTimeLeft = trafficLight.PresetYellowLightTimeLeft;

            ViewBag.RedLighttOn = trafficLight.RedLighttOn;
            ViewBag.YellowLightOn = trafficLight.YellowLightOn;
            ViewBag.GreenLightOn = trafficLight.GreenLightOn;

            ViewBag.RedLightTimeLeft = trafficLight.RedLightTimeLeft;
            ViewBag.YellowLightTimeLeft = trafficLight.YellowLightTimeLeft;
            ViewBag.GreenLightTimeLeft = trafficLight.GreenLightTimeLeft;

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        //[HttpPut]
        //[ActionName("PowerOn")]
        //public JsonResult PowerOn()
        //{
        //    var result = new JsonResult();
        //    try
        //    {
        //        Service.PowerOn();

        //        result.Data = new { Success = true, Message = "Sistema foi iniciado com Sucesso." };
        //    }
        //    catch (Exception ex)
        //    {
        //        result.Data = new Exception(ex.Message);
        //    }
        //    return result;
        //}

        //[HttpPut]
        //public JsonResult PowerOff()
        //{
        //    var result = new JsonResult();
        //    try
        //    {

        //        Service.PowerOff();

        //        result.Data = new { Success = true, Message = "Sistema foi parado com Sucesso." };
        //    }
        //    catch (Exception ex)
        //    {
        //        result.Data = new Exception(ex.Message);
        //    }
        //    return result;
        //}
    }
}

TrafficLightControllerSimulator2/Controllers/TrafficLightSimulators/TafficLightSimulatorController.cs
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrafficLightControllerSimulator2.Controllers
{
    public class TafficLightSimulatorController : Controller
    {
        TrafficLightSimulatorService Service = TrafficLightSimulatorService.GetInstance;
        public ActionResult Index()
        {
            ViewBag.TrafficLight = Service.GetTrafficLight();
            return View();
        }

        [HttpPost]
        public JsonResult PowerOn()
        {
            var result = new JsonResult();
            try
            {
                Service.PowerOn();

                result.Data = new { Success = true, Message = "Sistema foi iniciado com Sucesso." };
            }
            catch (Exception ex)
            {
                result.Data = new Exception(ex.Message);
            }
            return result;
        }

        [HttpPost]
        public JsonResult PowerOff()
        {
            var result = new JsonResult();
            try
            {

                Service.PowerOff();

                result.Data = new { Success = true, Message = "Sistema foi parado com Sucesso." };
            }
            catch (Exception ex)
            {
                result.Data = new Exception(ex.Message);
            }
            return result;
        }

        [HttpPost]
        public JsonResult PresetYellowLightTimeLeft(int presetValue)
        {
            var result = new JsonResult();
            try
            {

                Service.PresetYellowLightTimeLeft(presetValue);

                result.Data = new { Success = true, Message = "Novo tempo setado com sucesso." };
            }
            catch (Exception ex)
            {
                result.Data = new Exception(ex.Message);
            }
            return result;
        }

        [HttpPost]
        public JsonResult PresetGreenLightTimeLeft(int presetValue)
        {
            var result = new JsonResult();
            try
            {

                Service.PresetGreenLightTimeLeft(presetValue);

                result.Data = new { Success = true, Message = "Novo tempo setado com sucesso." };
            }
            catch (Exception ex)
            {
                result.Data = new Exception(ex.Message);
            }
            return result;
        }

        [HttpPost]
        public JsonResult PresetRedLightTimeLeft(int presetValue)
        {
            var result = new JsonResult();
            try
            {

                Service.PresetRedLightTimeLeft(presetValue);

                result.Data = new { Success = true, Message = "Novo tempo setado com sucesso." };
            }
            catch (Exception ex)
            {
                result.Data = new Exception(ex.Message);
            }
            return result;
        }
    }
}

TrafficLightControllerSimulator2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TrafficLightControllerSimulator2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TrafficLightControllerSimulator2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "TrafficLightSimulator";
}
<br />
<br />
<h2>Controlador Semáforos</h2>
<div>
    <br />
    <br />
    <div class="row">
        <div class="col-md-2">
            <button type="button" class="PowerOnSystem" onclick="PowerOnSystem();">
                <i></i> Ligar Sistema
            </button>
        </div>
        <div class="col-md-2">
            <button type="button" class="PowerOffSystem" onclick="PowerOffSystem();">
                <i></i> Desligar Sistema
            </button>
        </div>
    </div>
    <br />
    <br />
    <br />
    <div class="row">
        <div class="col-md-2">
            <label>Tempo para desligar luz Vermelha</label> </>
        </div>
        <div class="col-md-2">
            <label>Tempo para desligar luz Amarela</label> </>
        </div>
        <div class="col-md-2">
            <label>Tempo para desligar luz Verde</label> </>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-2">
            <input type="text" id="PresetRedLightTimeLeft" value="@ViewBag.PresetRedLightTimeLeft" />
            <br />
            <button type="button" class="PowerOffSystem" onclick="PresetRedLightTimeLeft();">
                <i></i> Salvar
            </button>
        </div>
        <div class="col-md-2">
            <input type="text" id="PresetYellowLightTimeLeft" value="@ViewBag.PresetYellowLightTimeLeft" />
            <br />
            <button type="button" class="PowerOffSystem" onclick="PresetYellowLightTimeLeft();">
                <i></i> Salvar
            </button>
        </div>
        <div class="col-md-2">
            <input type="text" id="PresetGreenLightTimeLeft" value="@ViewBag.PresetGreenLightTimeLeft" />
            <br />
            <button type="button" class="PowerOffSystem" onclick="PresetGreenLightTimeLeft();">
                <i></i> Salvar
            </button>
        </div>
    </div>
    @*viewComponent*@
    <div id="DinamicList">
        <br />
        <br />
        <br />
        <br />
        <div class="row col-md-4  table-bordered">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            Luz
                        </th>
                        <th>
                            Tempo para desligamento
                        </th>
                        <th>
                            Tempo restante
                        </th>
                        <th>
                            Status
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Vermelho</td>
                        <td>@ViewBag.PresetRedLightTimeLeft</td>
                        <td>@ViewBag.RedLightTimeLeft</td>
                        <td> @(ViewBag.RedLighttOn ? "Ligado":"Desligado")</td>
                    </tr>
                    <tr>
                        <td>Amarelo</td>
                        <td>@ViewBag.PresetYellowLightTimeLeft</td>
                        <td>@ViewBag.YellowLightTimeLeft</td>
                        <td> @(ViewBag.YellowLightOn ? "Ligado":"Desligado")</td>
                    </tr>
                    <tr>
                        <td>Verde</td>
                        <td>@ViewBag.PresetGreenLightTimeLeft</td>
                        <td>@ViewBag.GreenLightTimeLeft</td>
                        <td> @(ViewBag.GreenLightOn ? "Ligado":"Desligado")</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-2"></div>
        <div class="row col-md-4  table-bordered">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            Status Do Sistema
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@(ViewBag.On?"Ligado":"Desligado")</td>
                    </tr>
                </tbody>
            </table>
        </div>
        @*  *@
    </div>
   @*//<script src="toastr.js"></script>*@
    <script>
        function UpdatePage() {
            $.ajax({
                url: '@Url.Action("Index", "Home")',
                type: 'GET',
                dataType: 'html',
                success: function (data) {
                        var content = $(data).find("#DinamicList");
                        $("#DinamicList").replaceWith(content);
                },
                error: function () {
                    //toastr.error("Houve um erro ao processar a requisição.");
                    //console.log("alo");
                },
            });
        }

        setInterval('UpdatePage();', 1000);
       function PowerOnSystem() {
             $.ajax({
                url: '@Url.Action("PowerOn", "TafficLightSimulator")',
                type: 'post',
                dataType: 'json',
                //data: { transitionTIme : },
                success: function (data) {
                    if (data.Success) {
                        //toastr.success(data.Message);
                    }
                },
                error: function () {
                    //toastr.error("Houve um erro ao processar a requisição.");
                },
            });
       };

      function PowerOffSystem() {
       $.ajax({
                url: '@Url.Action("PowerOff", "TafficLightSimulator")',
                type: 'post',
                dataType: 'json',
                //data: { transitionTIme : },
                success: function (data) {
                    if (data.Success) {
                        //toastr.success(data.Message);
                    }
                },
                error: function () {
                    //toastr.error("Houve um erro ao processar a requisição.");
                },
            });
     };

        function PresetYellowLightTimeLeft() {
            var PresetYellowLightTimeLeft = $("#PresetYellowLightTimeLeft").val();
            $.ajax({
                url: '@Url.Action("PresetYellowLightTimeLeft", "TafficLightSimulator")',
                data: { presetValue: PresetYellowLightTimeLeft},
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.Success) {
                        window.location.reload();
                    }
                },
                error: function () {
                    //toastr.error("Houve um erro ao processar a requisição.");
                },
            });
        };

        function PresetGreenLightTimeLeft() {
            var PresetGreenLightTimeLeft = $("#PresetGreenLightTimeLeft").val();
            $.ajax({
                url: '@Url.Action("PresetGreenLightTimeLeft", "TafficLightSimulator")',
                data: { presetValue: PresetGreenLightTimeLeft },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.Success) {
                        window.location.reload();
                    }
                },
                error: function () {
                    //toastr.error("Houve um erro ao processar a requisição.");
                },
            });
     };

       function PresetRedLightTimeLeft() {
            var PresetRedLightTimeLeft = $("#PresetRedLightTimeLeft").val();
               $.ajax({
                url: '@Url.Action("PresetRedLightTimeLeft", "TafficLightSimulator")',
                data: { presetValue: PresetRedLightTimeLeft },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.Success) {
                        window.location.reload();
                    }
                },
                error: function () {
                    //toastr.error("Houve um erro ao processar a requisição.");
                },
            });
     };



    </script>

TrafficLightControllerSimulator2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title - Trafficlight Simulator</title>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trafficlight Simulator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrafficLightControllerSimulator2/Views/TafficLightSimulator/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>